### ISSUE TITLE
manage velocity of computer keyboard

### ISSUE THREAD

**Issue by josephlarralde** [scrime-u-bordeaux/midifile-performer-web#1]
Currently the notes are played at their original velocities.
There should be a layout on the keyboard with key positions defining velocities that should override the original ones.
Problem : how to get the user's keyboard layout in a web context ?
We could create maps for the most common ones (QWERTY, AZERTY, QWERTZ ?) and restrict to simple letter keys, then ask the user to choose their layout (and/or default to the layout of their ip's country when served from a dedicated non static server, e.g. with some [`node module`](https://www.npmjs.com/package/ip2country))

**Comment by josephlarralde** [comment]
This is what is now done (map for QWERTY and AZERTY layouts where letters are always guaranteed to be at the same positions). Bernard sent this snippet showing how it is done from the MidifilePerformer java application : 

```java
    static String[] qwerty = {
            "zxcvbnm,./",
            "asdfghjkl;'",
            "qwertyuiop[]\\",
            "1234567890-=",
    };

    static String[] azerty = {
            "wxcvbn,;:=",
            "qsdfghjklmù",
            "azertyuiop^$<",
            "@&é\"'{{è!à)-",
    };

    int getVelocity(int n) {
        if(master.config.velocityOnHeight) {
            Line d = new Line(shape.y, 128, shape.y+shape.height, 40);
            return(d.iget(SosMouse.y));
        }
        String[] map = master.config.qwerty ? qwerty : azerty;
        for(int i=0; i<map.length; i++) {
            int k = map[i].indexOf(n);
            if(k >= 0) return(30+i*15+(k/2));
        }
        return(100);
    }
```

**Comment by josephlarralde** [comment]
some suggestions :

- implement a keyboard row learn mode (what would be the alternative for more than 3 letter-only rows ?)
- allow the number pad to be a mini remote keyboard (as Jean is already doing in his max patch)
- allow the user to define a velocity for each row

some comments on the above suggestions : 

- all these settings should probably go into an "advanced settings" section

**Comment by NyuBlara** [comment]
(I will most likely be using this account, connected to my personal address, rather than the ENSEIRB account as my ENSEIRB address may be invalidated at any point during my mission)

Would it not be possible to the [key code](https://developer.mozilla.org/fr/docs/Web/API/KeyboardEvent/code) instead of the key's character ? This is (or should be) universal across keyboards.
