### ISSUE TITLE
UI/UX improvements to play modes selection

### ISSUE THREAD

**Issue by josephlarralde** [scrime-u-bordeaux/midifile-performer-web#13]
The midifile performer model allows to play a MIDI file automatically or manually.
Actually this is split into two modes in the interface (via two toggle buttons), and two clicks are needed to switch fro one mode to another.

We want to make the experience more fluid, so the the interface needs to be reworked.
There should be a unique classical transport interface, and we must determine the workflow to switch modes or make them coexist in some way.

More discussion is needed with the end users to write down a clear specification.

**Comment by NyuBlara** [comment]
Ideas after brainstorming : 
- Add a slide toggle between "Perform" and  "Play"
- When the toggle is on "Play", show a "Play"/"Pause" button
- When the toggle is on "Perform", hide the button

**Comment by rblard** [comment]
After further brainstorming, the toggle seems unnecessary. The [Score plugin implementation ](https://github.com/scrime-u-bordeaux/score-addon-midifileperformer) uses a principle we can imitate, where there is no "Interpret" button. Instead, there is a singular Play/Pause button, labeled "Play" at startup.

The Performer is put in "Interpret" mode by default. If the "Play" button is pressed at any point, passive playback begins and the button becomes "Pause". Playback can be stopped by inputting a MIDI command from the controller (in which case the button becomes "Play" again), or by pressing "Pause" ourselves.
