### ISSUE TITLE
Restricting range to single set produces no sound on input

### ISSUE THREAD

**Issue by rblard** [scrime-u-bordeaux/midifile-performer-web#23]
If the "start" and "end" flags of the scroll bar are positioned at the same set (= the same number, to loop on the same set), no sound is made when interpreting the file. This is not a problem for passive playback.

**Comment by josephlarralde** [comment]
I see. So either we forbid this, or we disable automatic playing when start and end are the same but still show a pause button and start playing as soon as the range increases ... ?

**Comment by rblard** [comment]
For me, it should entirely be possible to play one set in a loop.

**Comment by josephlarralde** [comment]
I agree. I just tested on the actual online version and it kind of works on the "first steps" page ... Once it didn't work when trying to loop on the very first set. Sometimes it stopped playing when I moved the loop points. Also the pause durations at the end of the loops all seem wrong, which I find weird I didn't notice before ... I hope this is a JS issue

**Comment by rblard** [comment]
I have trouble reproducing the bug. It might be gone. I'll leave this open for the time being.

**Comment by rblard** [comment]
I think I can reproduce one thing consistently : if the cursor is moved by dragging the start flag, the bug does not occur. But it seems to systematically occur if the end flag is dragged instead, as long as no passive playback has occurred on the file. Once that has happened, the bug seems to no longer occur.

**Comment by rblard** [comment]
This is confirmed to only be triggered by the end flag, because of an asymmetry in setting the start and end indices in the underlying library, where the second stops the performer, and the first does not.
