### ISSUE TITLE
displayed event set index on idle and while playing - undesired side effect

### ISSUE THREAD

**Issue by josephlarralde** [scrime-u-bordeaux/midifile-performer-web#27]
Actually, when idle, the displayed index corresponds to the next event set that will be played, although while playing the displayed index is the one of the set just played. This leads to confusion and is the root of an undesired behaviour : when automatic playing is turned off the index is not decremented, thus the last played event is played once again when we start playing again.
We should probably make another decision for the displayed index.
Here is a proposal : always display the index before the one that will next be played (0 when we are at the beginning, index - 1 otherwise). Would this help solving the issue ?

**Comment by rblard** [comment]
Pull request #30 proposes this : we keep the same index display, but prevent repetition of sets. This seems good enough, as it conserves the more instinctive display we already have but allows for the transition to happen the way we want it to.
